services:
  traefik:
    image: traefik:latest
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "9001:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro



networks:
  default:
    name: test-network
    external: true